// app/loan-upload/data.ts
export const loanData = {
    file_no: 'A0000559',
    state: 'Rajasthan',
    branch: 'Beawar',
    centre_name: 'Beawar',
    area: 'RAMGARH',
    quarter: '4th',
    entity_type: 'Individual',
    loan_category: 'General',
    loan_type: 'LAP',
    product: 'Property Loan',
    scheme_name: 'PROPERTY LOAN PARTIAL',
    gender: 'Male',
    customer_segment: 'Salaried',
    area_type: 'Rural',
    caste: 'ScheduledCaste',
    types_of_case: 'Cycle-1',
    loan_segment: 'General',
    property_type: 'Single Storey',
    mortgage_type: 'Registered',
    source_type: 'DST',
    loan_amount: 320000,
    installments: 60,
    interest: 23.0,
    disbursement_amount: 302673,
    emi: 9018,
    first_due_date: '2023-04-05',
    total_amt: 541257,
    last_due_date: '2028-03-05',
    installment_due_day: 5,
    repayment_type: 'EMI',
    disbursement_type: 'Transfer',
    disbursement_date: '2023-02-15',
    disbursement_status: 'Disbursed',
    processing_fee: 9600,
    service_tax: 1728,
    total_processing_fee: 11328,
    cersai_fee: 450,
    insurance_type: 'None',
    property_insurance: 100000,
    life_insurance: 1869,
    total_insurance: 1869,
    legal_charges: 1440,
    valuation_charges: 50,
    total_legal_charges: 2100,
    deductions: 17327,
    advance_emi: 2455,
    agreement_date: '2023-01-01',
    cibil_score: 658,
    loan_status: 'Active',
    property_value: 4500,
    property_area: 1700,
    work_profile_category: 'Salaried',
    work_sub_category: 'Cash Salary',
    work_profile: 'Cash Salary',
  };